resources:
  - name: docker-hello-world
    type: git
    icon: github
    source:
      uri: https://github.com/crccheck/docker-hello-world
  - name: kaniko-image
    type: docker-image
    icon: docker
    source:
      repository: gcr.io/kaniko-project/executor
      tag: debug  # debug version includes shell

jobs:
- name: build-hello-world
  plan:
  - get: docker-hello-world
  - get: kaniko-image
  - task: build-with-kaniko
    image: kaniko-image
    config:
      platform: linux
      inputs:
        - name: docker-hello-world
      run:
        path: /bin/sh
        args:
          - -c
          - |
            cd docker-hello-world
            /kaniko/executor --dockerfile=Dockerfile --context=$(pwd) --destination=172.17.0.1:5000/hello-world-local:latest
